### ISSUE TITLE
Kosovo: MP have different object for every term of office - should be merged

### ISSUE THREAD

**Issue by KrzysztofMadejski** [contributors-kodujdlapolski-pl/parldata-scrapers-Serbia-Albania-Kosovo#10]
http://api.parldata.eu/kv/kuvendi/people?where={%22name%22:%22Adem%20Grabovci%22}

All these objects should be one person with tracked changes

**Comment by KrzysztofMadejski** [comment]
MPs have different sites for each term of office.

MP's Pages should be processed from the last term to current and info should be updated using [effective_date](https://github.com/KohoVolit/api.parldata.eu/blob/master/USAGE.rst#automatic-tracking-of-changes) flag = chamber.founding_date.

**Comment by KrzysztofMadejski** [comment]
Informacje o pośle ze stron odpowiadających wszystkim kadencjom powinny być łączone w jeden obiekt. Obiekt posła powinien być aktualizowany informacjami poczynając od najstarszej do aktualnej kadencji. Zmiany będą zapisywane automatycznie, ale podczas wrzucania powinien być podawany parametr effective_change (PATCH /people?effective_change=<founding_date>) oznaczający faktyczną datę zmiany. Parametr ten powinien się równać początkowi przetwarzanej kadencji. 

https://github.com/KohoVolit/api.parldata.eu/blob/master/USAGE.rst#automatic-tracking-of-changes

**Comment by cakephp2bartek** [comment]
ERRRRRRORRRRR!!!!!!:    [body] => {"_status": "ERR", "_error": {"message": "Insertion failure: 1 document(s) contain(s) error(s)", "code": 422}, "_issues": {"effective_date": "unknown field"}}

{"id":"mp_AgimKrasniqi","name":"Agim Krasniqi","given_name":"Agim","family_name":"Krasniqi","sort_name":"Krasniqi Agim","image":"http:\/\/www.kuvendikosoves.org\/common\/images\/mp\/ldk_agim_krasniqi.jpg","sources":[{"url":"http:\/\/www.kuvendikosoves.org\/?cid=1,158,131&secid=102&legid=1"}],"effective_date":"2001-11-17"}

ze skype: to powinien miec ustawione:
effective_date = '2007-12-13'

**Comment by KrzysztofMadejski** [comment]
trzeba podac effective_date w parametrrach URL
[13:32:40] Krzysztof Madejski: ?effective_date=2011-11-11
[13:33:21] Krzysztof Madejski: czyli np. PATCH https://api.parldata.eu/kv/kuvendi/mp_xxx?effective_date=2011-11-11
[13:33:46] Krzysztof Madejski: albo w sumie PUT moze byc tez

**Comment by cakephp2bartek** [comment]
people wchodzą w kolejności od najstarszego do najnowszego
bez effective_date w url
