### ISSUE TITLE
Test speeches

### ISSUE THREAD

**Issue by KrzysztofMadejski** [contributors-kodujdlapolski-pl/parldata-scrapers-Serbia-Albania-Kosovo#13]
Please update https://docs.google.com/a/epf.org.pl/spreadsheets/d/1uNHub8-1MIqibT8kv5QkMPUmB705LSn0ZTD3-QcJ0K4/edit#gid=0 if ok

**Comment by KrzysztofMadejski** [comment]
@girogiro Is it ok? Can I close this issue?

**Comment by girogiro** [comment]
Give me two more days please.
