### ISSUE TITLE
Kosovo: no name

### ISSUE THREAD

**Issue by michalskop** [contributors-kodujdlapolski-pl/parldata-scrapers-Serbia-Albania-Kosovo#14]
There is no name for http://api.parldata.eu/kv/kuvendi/people/mp_3_VeziraEmrus and few others (mp_3_Et'hemÇeku, mp_3_HydajetHyseniKaloshi )

**Comment by KrzysztofMadejski** [comment]
Brak imion / nazwisk dla niektórych osób. Powinny być ustawiane pola: name, family_name, given_name, additinoal_name, sort_name, itd.  (a także sources)

Tutaj http://api.parldata.eu/kv/kuvendi/people/mp_3_VeziraEmrus, a także mp_3_Et'hemÇeku, mp_3_HydajetHyseniKaloshi

**Comment by KrzysztofMadejski** [comment]
"Name" (czyli pełne imię nazwisko) zawsze da się wypełnić tym co jest w źródle.
