### ISSUE TITLE
Kosovo: additional name instead of family name

### ISSUE THREAD

**Issue by michalskop** [contributors-kodujdlapolski-pl/parldata-scrapers-Serbia-Albania-Kosovo#15]
There are "aditional names" of people, while in Popolo, there are "family names"

**Comment by KrzysztofMadejski** [comment]
Nazwiska powinny być wpisywane do pola family_name, a nie additional_name.

http://api.parldata.eu/kv/kuvendi/people

**Comment by cakephp2bartek** [comment]
done

**Comment by cakephp2bartek** [comment]
done
