### ISSUE TITLE
kv/kuvendi: people: Dużo posłów jest stworzonych wyłącznie z samym ID

### ISSUE THREAD

**Issue by KrzysztofMadejski** [contributors-kodujdlapolski-pl/parldata-scrapers-Serbia-Albania-Kosovo#17]
Wielu już istnieje w bazie tylko jest jakiś problem z kodowaniem, np:
- http://api.parldata.eu/kv/kuvendi/people/mp_4_PaGrGoranMarinkovic
- http://api.parldata.eu/kv/kuvendi/people/mp_4_GoranMarinkovi%C3%A6

Ci którzy jednak nie istnieją powinni mieć przynajmniej wpisywane <name>, a najlepiej wszystkie pola: given_name, additional_name, family_name

Powinien też być zawsze parametr `sources` wypełniany, żeby można było zlokalizować skąd był pobierany

**Comment by cakephp2bartek** [comment]
to juz dodane

**Comment by KrzysztofMadejski** [comment]
Goran Marinkovic nadal się potwarza, ale to już jest spowodowane złym kodowaniem na stronie.
