### ISSUE TITLE
kv/kuvendi: people: Sorting

### ISSUE THREAD

**Issue by KrzysztofMadejski** [contributors-kodujdlapolski-pl/parldata-scrapers-Serbia-Albania-Kosovo#20]
> MPs should have set `sort_name` in the form "surname, given-name" to get order by surname in alphabetical list. Now they are ordered by first name.

Przy wstawianiu obiektów do people dodać pole `sort_name = "<Nazwisko> <Imie>"` z podstawionymi danymi, np. `sort_name="Kowalski Jan"`

**Comment by cakephp2bartek** [comment]
done
