### ISSUE TITLE
rs/skupstina: people: names

### ISSUE THREAD

**Issue by KrzysztofMadejski** [contributors-kodujdlapolski-pl/parldata-scrapers-Serbia-Albania-Kosovo#21]
Po pierwsze nazwisko powinno lądować w `family_name` zamiast `additional_name`, patrz http://api.parldata.eu/rs/skupstina/people/mp_%D0%88%D0%B5%D0%BB%D0%B5%D0%BD%D0%B0%D0%9C%D0%B8%D1%98%D0%B0%D1%82%D0%BE%D0%B2%D0%B8%D1%9B

Po drugie jeżeli jest podana imie i nazwiską cyrylicą i łaciną to powinna być wrzucana do pól name bardziej jedna wersja (zależnie od tego, która jest popularniejsza w innych zbiorach danych). Jeżeli są wykorzystywane obie to można wykorzystać pole `identifiers`.

Po trzecie imiona i nazwiska powinny być CamelCase.

Dla przykładu:
http://api.parldata.eu/rs/skupstina/people/mp_%C3%81rp%C3%A1dFremond%D0%90%D1%80%D0%BF%D0%B0%D0%B4%D0%A4%D1%80%D0%B5%D0%BC%D0%BE%D0%BD%D0%B4

Powinien być zapisany jako (w wersji cyrlica jest bardziej popularna):

``` json
{"given_name": "АРПАД ", // tylko że Camel Case
 "family_name": ФРЕМОНД", // tylko że Camel Case
 "name": "АРПАД ФРЕМОНД", // tylko że Camel Case
"sort_name": "ФРЕМОНД АРПАД ", // tylko że Camel Case
 "identifiers": [
   {"schema": "latin_name",
   "identifier": "Árpad Fremond"}
],
```

**Comment by cakephp2bartek** [comment]
done

**Comment by cakephp2bartek** [comment]
[body] => {"_error": {"code": 422, "message": "Insertion failure: 1 document(s) contain(s) error(s)"}, "_status": "ERR", "_issues": {"identifiers": {"0": {"schema": "unknown field"}}}}

**Comment by cakephp2bartek** [comment]
{"_error": {"code": 422, "message": "Insertion failure: 1 document(s) contain(s) error(s)"}, "_status": "ERR", "_issues": {"identifiers": "must be of list type"}}

**Comment by cakephp2bartek** [comment]
'schem>E<' => 'latin_name',
zmarnowany czas

**Comment by cakephp2bartek** [comment]
done
