### ISSUE TITLE
Po co są sleepy?

### ISSUE THREAD

**Issue by KrzysztofMadejski** [contributors-kodujdlapolski-pl/parldata-scrapers-Serbia-Albania-Kosovo#5]
https://github.com/contributors-kodujdlapolski-pl/parldata-scrapers-Serbia-Albania-Kosovo/blob/master/Model/QueleToSend.php#L123
https://github.com/contributors-kodujdlapolski-pl/parldata-scrapers-Serbia-Albania-Kosovo/blob/master/Model/QueleToSend.php#L132
https://github.com/contributors-kodujdlapolski-pl/parldata-scrapers-Serbia-Albania-Kosovo/blob/master/Model/QueleToSend.php#L141

https://github.com/contributors-kodujdlapolski-pl/parldata-scrapers-Serbia-Albania-Kosovo/search?utf8=%E2%9C%93&q=sleep

**Comment by cakephp2bartek** [comment]
mozesz wywalić ale licz się z tym że z albani dostaniesz bana, ja już mam :)
w przypadku QueleToSend, jest to wstrzymanie na 5sek jakby apiserwer padł i wywalił 500, ponieważ kolejki wysyłania są duże to wstrzymanie w takim przypadku daje szanse że serwer się odciąży

**Comment by KrzysztofMadejski** [comment]
brzmi sensownie!
