### ISSUE TITLE
Serbia: Nazwy kadencji powinny zawierać numer kadencji lub rok rozpoczęcia

### ISSUE THREAD

**Issue by KrzysztofMadejski** [contributors-kodujdlapolski-pl/parldata-scrapers-Serbia-Albania-Kosovo#9]
Oprócz Народна скупштина Републике Србије
powinien być numerek lub rok (cokolwiek pozwalającego na identyfikację)

**Comment by KrzysztofMadejski** [comment]
Widzę, że na stronie jest rok. Niech więc <name> będzie równe:
Народна скупштина Републике Србије - 2012
Народна скупштина Републике Србије - 2008
Народна скупштина Републике Србије - 2007
itd.

**Comment by cakephp2bartek** [comment]
done
